Repository stolostron/search-e2e-test, pull requests merged in 2022-02, with the labels that each got.

#179 [release-2.3] update org reference to stolostron
  .travis.yml
  COMPONENT_VERSION
  Makefile
  README.md
  package.json
  tests/cypress/README.md
Labels: lgtm

#180 [release-2.4] update org reference to stolostron
  Makefile
  package.json
  tests/cypress/README.md
Labels: lgtm, approved

#182 [release-2.4] Updated file formatting with prettier
  .prettierignore
  .prettierrc.json
  Dockerfile
  Makefile.prow
  build/upload-to-s3.sh
  cicd-scripts/run-prow-e2e.sh
  cicd-scripts/run-prow-unit.sh
  config/index.js
  install-dependencies.sh
  jest.config.js
  package-lock.json
  package.json
  start-tests.sh
  tests/api/access.test.js
  tests/api/common.test.js
  tests/api/filter.test.js
  tests/api/managed.test.js
  tests/api/search.test.js
  tests/common-lib/clusterAccess.js
  tests/cypress/config/index.js
  tests/cypress/scripts/cliHelper.js
  tests/cypress/tests/01-common/01-common-searches.spec.js
  tests/cypress/tests/02-search/01-search.spec.js
  tests/cypress/tests/02-search/02-pod-logs.spec.js
  tests/cypress/tests/03-create/01-create-resource.spec.js
  tests/cypress/tests/04-edit/01-scale.spec.js
  tests/cypress/tests/05-delete/01-delete-resources.spec.js
  tests/cypress/tests/06-filter/01-filters.spec.js
  tests/cypress/tests/07-link/01-cluster-page-search-link.spec.js
  tests/cypress/tests/08-overview/01-overview-page.spec.js
  tests/cypress/tests/09-saved/01-saved-searches.spec.js
  tests/cypress/tests/10-suggested/01-suggested-searches.spec.js
  tests/cypress/tests/11-managed/01-verify-managed-cluster.spec.js
  tests/cypress/tests/11-managed/02-multicluster-search-base.spec.js
  tests/cypress/tests/12-rbac/01-view-overview-with-rbacuser.spec.js
Labels: lgtm, approved

#181 [release-2.5] Updated file formatting with prettier
  .prettierignore
  .prettierrc.json
  Dockerfile
  Makefile.prow
  cicd-scripts/run-prow-e2e.sh
  cicd-scripts/run-prow-unit.sh
  config/index.js
  install-dependencies.sh
  jest.config.js
  package.json
  start-tests.sh
  tests/api/access.test.js
  tests/api/common.test.js
  tests/api/filter.test.js
  tests/api/managed.test.js
  tests/api/search.test.js
  tests/common-lib/clusterAccess.js
  tests/cypress/config/index.js
  tests/cypress/scripts/cliHelper.js
  tests/cypress/tests/01-common/01-common-searches.spec.js
  tests/cypress/tests/02-search/01-search.spec.js
  tests/cypress/tests/02-search/02-pod-logs.spec.js
  tests/cypress/tests/03-edit/01-scale.spec.js
  tests/cypress/tests/04-delete/01-delete-resources.spec.js
  tests/cypress/tests/05-filter/01-filters.spec.js
  tests/cypress/tests/06-link/01-cluster-page-search-link.spec.js
  tests/cypress/tests/07-overview/01-overview-page.spec.js
  tests/cypress/tests/08-saved/01-saved-searches.spec.js
  tests/cypress/tests/09-suggested/01-suggested-searches.spec.js
  tests/cypress/tests/10-managed/01-verify-managed-cluster.spec.js
  tests/cypress/tests/10-managed/02-multicluster-search-base.spec.js
  tests/cypress/tests/11-rbac/01-view-overview-with-rbacuser.spec.js
  tests/cypress/views/clusters.js
Labels: lgtm, approved

#186 Rebuilding search e2e image
  README.md
Labels: lgtm, approved

#187 Updated package.json to use cypress version 8.5.0
  package-lock.json
  package.json
Labels: lgtm, approved

#185 Publish script to debug RHACM Redis
  debug-scripts/redis-debug.sh
Labels: lgtm, do-not-merge/hold, approved

#176 [release-2.4] prow jobs fix
  .travis.yml
  Dockerfile
  Makefile.prow
  build/rbac-setup.sh
  build/upload-to-s3.sh
  cicd-scripts/run-prow-e2e.sh
  cicd-scripts/run-prow-unit.sh
  package-lock.json
  package.json
  start-tests.sh
Labels: approved

#175 [release-2.5] prow jobs fix
  Dockerfile
  build/rbac-setup.sh
  build/upload-to-s3.sh
  cicd-scripts/run-prow-e2e.sh
  cicd-scripts/run-prow-unit.sh
  package-lock.json
  package.json
  start-tests.sh
  tests/common-lib/clusterAccess.js
  tests/cypress/views/overview.js
Labels: lgtm, approved

#188 Disabled managed cluster test
  .github/workflows/package-dependencies-update.yml
  tests/cypress/tests/02-search/02-pod-logs.spec.js
Labels: lgtm, approved

#189 Updated package dependencies automation
  .github/workflows/package-dependencies-update.yml
  tests/cypress/tests/02-search/02-pod-logs.spec.js
Labels: lgtm, approved
